# Generated by Django 5.2.1 on 2025-06-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.AddField(
            model_name='testresult',
            name='awarded_coin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
