# Generated by Django 5.2.1 on 2025-06-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_test_correct_answer_remove_test_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinwithdrawrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='nanocointransaction',
            name='student',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='student',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='CoinWithdrawRequest',
        ),
        migrations.DeleteModel(
            name='NanoCoinTransaction',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
