# Generated by Django 5.2.1 on 2025-06-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_test_description_alter_test_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='group',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='student',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
