# Generated by Django 5.2.1 on 2025-06-27 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_question_answer'),
        ('users', '0007_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttest',
            name='earned_coins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tests', to='accounts.test'),
        ),
    ]
