# Generated by Django 5.2.1 on 2025-07-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_studenttest_earned_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
