# Generated by Django 5.2.1 on 2025-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_rename_requested_at_coinwithdrawrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nanocointransaction',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='nanocointransaction',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
