# Generated by Django 5.2.1 on 2025-06-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_student_group_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lesson_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='lesson_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
