# Generated by Django 5.2.1 on 2025-06-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
