# Generated by Django 5.2.1 on 2025-06-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nanocoin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
