# Generated by Django 5.2.1 on 2025-06-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
    ]
