# Generated by Django 5.2.1 on 2025-07-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_customuser_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cash_balance',
            field=models.PositiveIntegerField(default=0, help_text='Student pul balansi (so‘m)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nanocoin',
            field=models.PositiveIntegerField(default=0, help_text='Student coin balansi'),
        ),
        migrations.DeleteModel(
            name='NanoCoinTransaction',
        ),
    ]
